### ISSUE TITLE
Installing Metrics : Crash Loop Back-off 

### ISSUE THREAD

**Issue by bschraven** [Microsoft/openshift-origin#69] opened 2018-03-01 08:56 UTC
Hello,

i try to install OpenShift in Azure with this Repo. Anything is working fine, but de Metrics.
The Hawkular Metrics Pod ist everytime Crash Loop Back-off.

This is logged :
```
2018-03-01 08:42:24 Starting Hawkular Metrics
unable to write 'random state'
unable to write 'random state'
The service account has read permissions for its project. Proceeding
The service account has permission to watch namespaces. Proceeding
Creating the Hawkular Metrics keystore from the Secret's cert data
unable to write 'random state'
Converting the PKCS12 keystore into a Java Keystore
Importing keystore /opt/hawkular/auth/hawkular-metrics.pkcs12 to /opt/hawkular/auth/hawkular-metrics.keystore...
Entry for alias hawkular-metrics successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
[Storing /opt/hawkular/auth/hawkular-metrics.keystore]
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /opt/hawkular/auth/hawkular-metrics.keystore -destkeystore /opt/hawkular/auth/hawkular-metrics.keystore -deststoretype pkcs12".
Building the trust store
Certificate was added to keystore
Certificate was added to keystore
Splitting up the Kubernetes CA into individual certificates
Adding the Kubernetes CAs into the trust store
Certificate was added to keystore
Retrieving the Logging's CA and adding to the trust store, if Logging is available
Could not get the logging secret! Status code: 403. The Hawkular Alerts integration with Logging might not work properly.
---------------------------
  JBoss Bootstrap Environment
  JBOSS_HOME: /opt/jboss/wildfly
  JAVA: /usr/lib/jvm/java/bin/java
  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager -Djava.awt.headless=true -Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.PollSelectorProvider  -Xbootclasspath/p:/opt/jboss/wildfly/bin/alpn-boot-8.1.7.v20160121.jar -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump
---------------------------
Could not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:348)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at java.util.logging.LogManager$1.run(LogManager.java:195)
	at java.util.logging.LogManager$1.run(LogManager.java:181)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:181)
	at org.jboss.modules.Main.main(Main.java:480)
WARNING: Failed to load the specified log manager class org.jboss.logmanager.LogManager
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/logmanager/Level
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jboss.modules.Module.run(Module.java:320)
	at org.jboss.modules.Main.main(Main.java:505)
Caused by: java.lang.ClassNotFoundException: org.jboss.logmanager.Level
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:348)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
... 4 more
```

I installed the complete Cluster again and again, every Time with same Results.

Some weeks ago a Collegue installed the Cluster (also in 3.7), he had no problems with this.

**Comment by valtynikov** [comment] 2018-03-15 13:36
@bschraven I ran into the same exact issue with metrics in a brand new cluster. Please let me know if you found a solution or a workaround. I had to disable metrics for now.

**Comment by swe-covis** [comment] 2018-03-29 21:28
This seems to be caused by newer docker images for the metrics part (3.7.2/3.9). 
You can get it up and running by specifying the variable "openshift_hosted_metrics_deployer_version" on execution of the metrics playbook, pointing to the currently installed version of Openshift Origin on your host(s):

```shell
ansible-playbook openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml -e openshift_metrics_install_metrics=True -e openshift_metrics_cassandra_storage_type=dynamic -e  openshift_hosted_metrics_deployer_version=v3.7.1
```
The currently installed version of Origin can be detected by running
```shell
rpm -q origin | cut -d'-' -f 2
```

I ran into the same issue and was able to fix it by just running the metrics playbook again with setting the "openshift_hosted_metrics_deployer_version" to the currently installed version of Origin as described above.  

Please take a look at PR #72 for a possible solution that includes the version detection into the main script.

**Comment by swe-covis** [comment] 2018-04-04 08:28
@bschraven PR #72 has been merged - would you consider to give it another try and close this issue on success?

**Comment by haroldwongms** [comment] 2018-05-19 01:14
PR was issued to address this problem.  No response from original complaint for over a month so closing this issue.

**Closed by haroldwongms** 2018-05-19 01:14 UTC
